In [1]:
import numpy as np
import pandas as pd

In [2]:
# Read file
fopen = open("a.txt")

for f in fopen:
    print(f)

6 4 5 2 1000

2 0 rue-de-londres 1

0 1 rue-d-amsterdam 1

3 1 rue-d-athenes 1

2 3 rue-de-rome 2

1 2 rue-de-moscou 3

4 rue-de-londres rue-d-amsterdam rue-de-moscou rue-de-rome

3 rue-d-athenes rue-de-moscou rue-de-londres



In [3]:
# Read file
fopen = open("a.txt")
firstline = fopen.readline().split()

# First line

# Duration
D = int(firstline[0])

# Intersections
I = int(firstline[1])

# Streets
S = int(firstline[2])

# num cars
V = int(firstline[3])

# Point for each car
F = int(firstline[4])

print(firstline)

['6', '4', '5', '2', '1000']


In [4]:
# Create a weighted matrix
weighted = np.zeros((I,I))
# print(weighted)

# Dictionary of streets
streets = {}

for i in range(S):
    each_line = fopen.readline().split()
    print(each_line)
    weighted[int(each_line[0]), int(each_line[1])] = 1
    # Set path for each street - intersection start to end, time it takes for car
    streets[each_line[2]] = (int(each_line[0]), int(each_line[1]), int(each_line[3]))

print()
print(streets)
print()
print(weighted)

['2', '0', 'rue-de-londres', '1']
['0', '1', 'rue-d-amsterdam', '1']
['3', '1', 'rue-d-athenes', '1']
['2', '3', 'rue-de-rome', '2']
['1', '2', 'rue-de-moscou', '3']

{'rue-de-londres': (2, 0, 1), 'rue-d-amsterdam': (0, 1, 1), 'rue-d-athenes': (3, 1, 1), 'rue-de-rome': (2, 3, 2), 'rue-de-moscou': (1, 2, 3)}

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 1.]
 [0. 1. 0. 0.]]


In [5]:
#Printing sequence of intersections each car has to go through
paths = {}

for car in range(V):
    car_line = fopen.readline().split()
    cnt = 0
    paths[car] = []
    for j in range(1,len(car_line)):
        paths[car].append(streets[car_line[j]][1])

print(paths)

{0: [0, 1, 2, 3], 1: [1, 2, 0]}
